version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: my_postgres_container
    ports:
      - "5051:5051"
    environment:
      POSTGRES_USER: subham
      POSTGRES_PASSWORD: subham123
      POSTGRES_DB: chatapp
    volumes:
      - my_postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  my_postgres_data: