"use client";
import React from "react";
import { Column, DataRow } from "./SubTableTypes";
import { Table } from "./Table";
import { DatePicker } from 'antd';
import AntTable from "@/app/components/admin/components/Table/AntTable";
import BgAdminTailwindWrapper from "@/app/components/admin/components/TailwindWrapper/BgTailwindWrapper";

const rows: DataRow[] = [
    {
        token: "ETH",
        price: 0.0,
        lastUpdated: "0.0",
        tradingDate: "0.0",
        buys: 0.0,
        sells: 0.0,
        txns: 0.0,
        volume: 0.0,
        liquidity: 0.0,
        fdv: 0.0,
    },
    {
        token: "PULSE",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "BNB",
        price: 2.0,
        lastUpdated: "9.0",
        tradingDate: "2.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "ARBITRUM",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "KCC",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "FDKCC",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "EEE",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "SFSF",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "GSF",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "RTT",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "KJKJ",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "SFSFS",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "AFAF",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "GGYH",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "AAS",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "HHHDA",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "ASG",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "JJDC",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "CCED",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "ZZYU",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "GGGSSA",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "NNM",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "DDRH",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
    {
        token: "JSSA",
        price: 2.0,
        lastUpdated: "3.0",
        tradingDate: "0.6",
        buys: 8.0,
        sells: 0.9,
        txns: 1.0,
        volume: 8.5,
        liquidity: 6.5,
        fdv: 3.6,
    },
];
const columns: Column[] = [
    {
        id: "token",
        label: "Token",
        minWidth: "150px",
        align: "left",
    },
    {
        id: "price",
        label: "Price",
        minWidth: "150px",
        align: "right",
    },
    {
        id: "lastUpdated",
        label: "Last Updated",
        minWidth: "150px",
        align: "left",
    },
    {
        id: "tradingDate",
        label: "Trading Date",
        minWidth: "150px",
        align: "left",
    },
    {
        id: "buys",
        label: "Buys",
        minWidth: "150px",
        align: "left",
    },
    {
        id: "sells",
        label: "Sells",
        minWidth: "150px",
        align: "left",
    },
    {
        id: "txns",
        label: "TXNS",
        minWidth: "150px",
        align: "left",
    },
    {
        id: "volume",
        label: "Volume",
        minWidth: "150px",
        align: "left",
    },
    {
        id: "liquidity",
        label: "Liquidity",
        minWidth: "150px",
        align: "left",
    },
    {
        id: "fdv",
        label: "FDV",
        minWidth: "150px",
        align: "left",
    }
];
const Bitrock = () => {
    return (
        <div>
            {/*<BitRock />*/}
            {/*<DatePicker />*/}
            <BgAdminTailwindWrapper><AntTable/></BgAdminTailwindWrapper>
        </div>
    );
};
export default Bitrock;

const BitRock = () => {
    return (
        <div className="w-96 sm:w-[50%] md:w-[50%] lg:w-[100%]  ">
        <Table columns={columns} rows={rows} />
    </div>
);
};
