import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import React from "react";
import Navbar from "@/app/components/Navbar/Navbar";
import ThemeProviders from "@/app/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" h-full">
      <ThemeProviders>
        <body className={`${inter.className}bg-gray-300 dark:bg-slate-900`}>
          <div className="lg:mx-12">
            <Navbar />
            {children}
          </div>
        </body>
      </ThemeProviders>
    </html>
  );
}
