version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5050:5050"  # Map host port 5050 to container port 5050
    depends_on:
      - redis
  redis:
    image: "redis/redis-stack:latest"
    container_name: "redis-stack"
    environment:
      - REDIS_ARGS=--save 1200 32
    ports:
      - "6379:6379"  # Map host port 6379 to container port 6379
      - "8001:8001"  # Map host port 8001 to container port 8001
